FROM node:18-buster

RUN apt-get update && \
    apt-get install -y docker.io curl && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && \
    mv kubectl /usr/local/bin/ && \
    ln -s /usr/bin/docker /usr/local/bin/docker

ENV PATH="/usr/local/bin:${PATH}"

WORKDIR /app

CMD ["sh"]
